project_id = "ghmxlercrwilpdmxxsab"

[functions.ai-career-agent]
verify_jwt = false

[functions.scrape-job]
verify_jwt = false

[functions.elevenlabs-conversation]
verify_jwt = false

[functions.generate-interview]
verify_jwt = false

[functions.career-counselor]
verify_jwt = false
